In [1]:
# Importing libraries
import numpy as np
import pandas as pd
import yfinance as yf
import talib as ta
from datetime import datetime, date

# Disabling warnings
import warnings
warnings.filterwarnings("ignore")

# Stock ticker
ticker = 'AMZN'

# Downloading stock data from yahoo finance
df = yf.download(ticker, start="2021-11-01", end=datetime.today(), progress=False)[['Open', 'High', 'Low', 'Close', 'Volume']]

# Check if any zero volumes are available
indexZeros = df[ df['Volume'] == 0 ].index

# Cleaning data for null values
df.drop(indexZeros , inplace=True)
df.loc[(df["Volume"] == 0 )]

Empty DataFrame
Columns: [Open, High, Low, Close, Volume]
Index: []

In [2]:
# Calculating indicators using TA-Lib
df['MACD'] = ta.MACD(df['Close'])[0]
df['ATR'] = ta.ATR(df['High'], df['Low'], df['Close'], 20)
df['RSI'] = ta.RSI(df['Close'])
df['Average'] = ta.AVGPRICE(df['Open'], df['High'], df['Low'], df['Close']) #midprice
df['MA40'] = ta.SMA(df['Average'], 40)
df['MA80'] = ta.SMA(df['Average'], 80)
df['MA160'] = ta.SMA(df['Average'], 160)

In [3]:
# Number of days to calculate slope
backrolling = 6

# Calculating slope for indicators
df['slopeMA40'] = ta.LINEARREG_SLOPE(df['MA40'], backrolling)
df['slopeMA80'] = ta.LINEARREG_SLOPE(df['MA80'], backrolling)
df['slopeMA160'] = ta.LINEARREG_SLOPE(df['MA160'], backrolling)
df['slopeAverage'] = ta.LINEARREG_SLOPE(df['Average'], backrolling)
df['slopeRSI'] = ta.LINEARREG_SLOPE(df['RSI'], backrolling)
df['slopeMACD'] = ta.LINEARREG_SLOPE(df['MACD'], backrolling)

df.tail()

,Open,High,Low,Close,Volume,MACD,ATR,RSI,Average,MA40,MA80,MA160,slopeMA40,slopeMA80,slopeMA160,slopeAverage,slopeRSI,slopeMACD
Date,,,,,,,,,,,,,,,,,,
2023-09-19,138.699997,138.839996,135.559998,137.630005,61482500,1.779987,3.363401,49.789945,137.682499,136.113125,131.775594,116.819594,0.243389,0.318543,0.271120,-0.890572,-2.826545,0.000117
2023-09-20,138.550003,139.369995,135.199997,135.289993,46263700,1.301422,3.403730,45.512965,137.102497,136.312250,132.043094,117.037766,0.230411,0.304632,0.253488,-1.465358,-4.298499,-0.183310
2023-09-21,131.940002,132.240005,129.309998,129.330002,70234800,0.436205,3.532544,36.834181,130.705002,136.393313,132.196688,117.205985,0.199923,0.271132,0.228030,-2.461714,-5.097082,-0.382185
2023-09-22,131.110001,132.029999,128.520004,129.119995,59859500,-0.263395,3.531416,36.569566,130.195000,136.400250,132.302844,117.322766,0.151862,0.225880,0.199177,-2.485357,-4.337648,-0.524618
2023-09-25,129.360001,131.779999,128.770004,131.270004,45964600,-0.637002,3.505345,41.224891,130.295002,136.381125,132.421407,117.480938,0.093436,0.180354,0.175525,-2.262071,-3.287907,-0.594677

In [4]:
# Target flexible way
ask = 0.05      #ask
riskRatio = 2   #reward/risk ratio

# Identifying future trend for each day
def mytarget(barsupfront, df1):
    length = len(df1)
    high = list(df1['High'])
    low = list(df1['Low'])
    close = list(df1['Close'])
    open = list(df1['Open'])
    trendcat = [None] * length
    
    for line in range (0,length-barsupfront-2):
        valueOpenLow = 0
        valueOpenHigh = 0
        for i in range(1,barsupfront+2):
            value1 = 1-(low[line+i]/open[line+1])
            value2 = 1-(high[line+i]/open[line+1])
            valueOpenLow = max(value1, valueOpenLow)
            valueOpenHigh = min(value2, valueOpenHigh)

            # Downtrend 
            if ( (valueOpenLow >= ask) and (-valueOpenHigh <= (ask/riskRatio)) ):
                trendcat[line] = 1
                break

            # Uptrend
            elif ( (valueOpenLow <= (ask/riskRatio)) and (-valueOpenHigh >= ask) ):
                trendcat[line] = 2
                break
            
            # No clear trend
            else:
                trendcat[line] = 0
            
    return trendcat

In [5]:
# mytarget(barsfront to take into account, dataframe)
df['mytarget'] = mytarget(21, df)
df.head()

,Open,High,Low,Close,Volume,MACD,ATR,RSI,Average,MA40,MA80,MA160,slopeMA40,slopeMA80,slopeMA160,slopeAverage,slopeRSI,slopeMACD,mytarget
Date,,,,,,,,,,,,,,,,,,,
2021-11-01,168.089996,168.792999,164.600998,165.905502,72178000,NaN,NaN,NaN,166.847374,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
2021-11-02,165.750504,166.556000,164.177505,165.637497,52552000,NaN,NaN,NaN,165.530376,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
2021-11-03,165.449997,169.746002,164.876007,169.199997,67944000,NaN,NaN,NaN,167.318001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
2021-11-04,168.500000,174.931503,168.250000,173.850006,107060000,NaN,NaN,NaN,171.382877,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
2021-11-05,173.850006,178.312500,173.848999,175.949493,99940000,NaN,NaN,NaN,175.490250,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0

In [6]:
# Attributes to train and test the model
attributes=['ATR', 'RSI', 'MACD', 'Average', 'MA40', 'MA80', 'MA160', 'slopeMA40', 'slopeMA80', 'slopeMA160', 'slopeAverage', 'slopeRSI', 'slopeMACD']

df      = df[['Volume', 'MACD', 'ATR', 'RSI', 'Average', 'MA40', 'MA80', 'MA160', 'slopeMA40', 'slopeMA80', 'slopeMA160', 'slopeAverage', 'slopeRSI', 'slopeMACD', 'mytarget']] 
df_model= df[df.index<datetime.strptime("2022-11-01", "%Y-%m-%d")]
df_test = df[df.index>=datetime.strptime("2022-11-01", "%Y-%m-%d")]

# Separating today's data for prediction
x_today = df_model[attributes][-1:]

# Dropping all rows with null values
df_model=df_model.dropna()

# Creating Input and Output dataset
x = df_model[attributes]
y = df_model["mytarget"]

df_model.tail()

,Volume,MACD,ATR,RSI,Average,MA40,MA80,MA160,slopeMA40,slopeMA80,slopeMA160,slopeAverage,slopeRSI,slopeMACD,mytarget
Date,,,,,,,,,,,,,,,
2022-10-25,50934600,-1.164798,4.747901,54.169981,120.129999,120.333500,124.318469,128.085594,-0.413927,0.098446,-0.176434,0.805929,1.713232,0.433295,0.0
2022-10-26,68802300,-1.169588,4.802505,46.500584,116.442501,120.001437,124.394313,127.944833,-0.373102,0.119801,-0.152939,0.703786,0.775538,0.408374,1.0
2022-10-27,129605400,-1.534942,4.856880,40.609602,112.192499,119.596562,124.374750,127.731731,-0.349841,0.106108,-0.147283,-0.455929,-1.272868,0.267614,2.0
2022-10-28,223133400,-2.405975,5.279036,33.309477,100.735003,118.955562,124.194375,127.439227,-0.379050,0.047412,-0.170434,-3.035857,-4.001477,-0.026733,1.0
2022-10-31,99251400,-3.138368,5.221585,32.501108,102.902500,118.310750,124.041875,127.182105,-0.454257,-0.028803,-0.205394,-4.110643,-4.889666,-0.330203,1.0

In [7]:
# KNN Machine Learning Libraries
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

# Splitting training and testing data
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

# Using XgBoost Classifier
from xgboost import XGBClassifier

# Training
model2 = XGBClassifier()
model2.fit(X_train, y_train)

# Prediction
pred_train = model2.predict(X_train)
pred_test = model2.predict(X_test)

# Accuracy
acc_train = accuracy_score(y_train, pred_train)
acc_test = accuracy_score(y_test, pred_test)

print('****Train Results****')
print("Accuracy: {:.4%}".format(acc_train))
print('****Test Results****')
print("Accuracy: {:.4%}".format(acc_test))

[12:16:16] WARNING: C:\Windows\Temp\abs_557yfx631l\croots\recipe\xgboost-split_1659548953302\work\src\learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
****Train Results****
Accuracy: 100.0000%
****Test Results****
Accuracy: 44.4444%

## XGBoost with Sequential Sampling

_makes more sense for model to learn sequentially_

In [ ]:
#random sampling
#X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=10)

# Note: Above examples were made using random sampling 

#sequential sampling
train_index = int(0.8 * len(x))
X_train, X_test = x[:train_index], x[train_index:]
y_train, y_test = y[:train_index], y[train_index:]

model3 = XGBClassifier()
model3.fit(X_train, y_train)
pred_train = model3.predict(X_train)
pred_test = model3.predict(X_test)
acc_train = accuracy_score(y_train, pred_train)
acc_test = accuracy_score(y_test, pred_test)
print('****Train Results****')
print("Accuracy: {:.4%}".format(acc_train))
print('****Test Results****')
print("Accuracy: {:.4%}".format(acc_test))